# This workflow will run unit tests based on latest data version

name: Unit Tests

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: 'developer'
      MYSQL_PASS: 'developer'
    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Default MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql user: ${{ env.MYSQL_USER }}
          mysql password: ${{ env.MYSQL_PASS }}

      - name: Import Data
        env:
          ONCOKB_OAUTH_TOKEN: ${{ secrets.ONCOKB_OAUTH_TOKEN }}
        run: |
          MYSQL_FILE_NAME=mysql.sql.gz
          curl -s https://"${ONCOKB_OAUTH_TOKEN}"@raw.githubusercontent.com/knowledgesystems/oncokb-data/master/RELEASE/latest/"${MYSQL_FILE_NAME}" -O
          echo ${MYSQL_USER}

          mysql -u${MYSQL_USER} -p${MYSQL_PASS} -e "CREATE DATABASE IF NOT EXISTS test"
          zcat "${MYSQL_FILE_NAME}" | mysql -u${MYSQL_USER} -p${MYSQL_PASS} test

      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Run unit tests
        run: |
          mvn -ntp test \
          -Djdbc.driverClassName=com.mysql.jdbc.Driver \
          -Djdbc.url=jdbc:mysql://localhost:3306/test \
          -Djdbc.username=root \
          -Djdbc.password=root

