# This workflow will run unit tests based on latest data version

name: Unit Tests

on: push 

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASS: 'developer'
    steps:
      - uses: actions/checkout@v2

      - name: Shutdown Default MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7'
          mysql database: 'test'
          mysql root password: ${{ env.MYSQL_ROOT_PASS }}

      - name: Wait for MySQL
        env:
          ONCOKB_OAUTH_TOKEN: ${{ secrets.ONCOKB_OAUTH_TOKEN }}
          MYSQL_PASS: ${{ env.MYSQL_PASS }}
        run: |
          while ! mysqladmin ping --host=127.0.0.1 --user=root --password=$MYSQL_ROOT_PASS --silent; do
            sleep 1
          done

      - name: Import Data
        env:
          ONCOKB_OAUTH_TOKEN: ${{ secrets.ONCOKB_OAUTH_TOKEN }}
          MYSQL_ROOT_PASS: ${{ env.MYSQL_ROOT_PASS }}
        run: |
          MYSQL_FILE_NAME=mysql.sql.gz
          curl -s https://"${ONCOKB_OAUTH_TOKEN}"@raw.githubusercontent.com/knowledgesystems/oncokb-data/master/RELEASE/latest/"${MYSQL_FILE_NAME}" -O
          echo ${MYSQL_USER}

          mysql --host=127.0.0.1 --user=root --password="${MYSQL_ROOT_PASS}" -e "CREATE DATABASE IF NOT EXISTS test"
          zcat "${MYSQL_FILE_NAME}" | mysql --host=127.0.0.1 --user=root --password="${MYSQL_ROOT_PASS}" test

      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'

      - name: Run unit tests
        env:
          MYSQL_ROOT_PASS: ${{ env.MYSQL_ROOT_PASS }}
        run: |
          mvn -ntp test \
          -Djdbc.driverClassName=com.mysql.jdbc.Driver \
          -Djdbc.url=jdbc:mysql://127.0.0.1:3306/test \
          -Djdbc.username=root \
          -Djdbc.password=${MYSQL_ROOT_PASS}

